server:
  port: 8762
spring:
  application:
    #服务名  每个不同业务微服务名需唯一
    name: user-lei
eureka:
  instance:
    # 指定此实例的ip
    ip-address: 192.168.124.17
    #显示Ip 注册
    prefer-ip-address: true
    # 注册时使用ip而不是主机名
    instance-id: ${eureka.instance.ip-address}:${server.port}
  client:
    service-url:
      #eureka注册中心地址
      defaultZone: http://localhost:8761/eureka
