server:
  port: 6001
spring:
  application:
    #服务名配置
    name: app-gateway
  cloud:
    gateway:
#      default-filters:
#        - AddResponseHeader=X-Response-Default, panghu
#        - PrefixPath=/lei-app
      routes:
        #简单的路由
        - id: easy-order
          uri: http://localhost:9002/
          predicates:
            - Path=/order/**
        #根据服务名路由
        - id: server-order
          uri: lb://demo-order
          predicates:
            - Path=/order/**
        - id: server-product
          uri: lb://demo-product
          predicates:
            - Path=/product/**,/zs/{aa}
#            - After=2020-10-13T21:57:33.993+08:00[Asia/Shanghai]
#            - Before=2020-10-13T22:12:33.993+08:00[Asia/Shanghai]
#            - Between=2020-10-13T22:24:33.993+08:00[Asia/Shanghai],2020-10-13T22:26:33.993+08:00[Asia/Shanghai]
#            - Cookie=username,^[a-zA-z].*
#            - Method=GET,POST
#            - Header=Authentication,leilei
#            - Header=Authentication,\d+
#            - Weight=testWeight, 1
#            - Query=name,AA.
#            - Host=**.zsls.org,**.anotherhost.org
#            - RemoteAddr=192.168.124.1/32
          filters:
#            - AddRequestHeader=X-Request-lei,man
#            - AddRequestParameter=name,basketball
#            - AddResponseHeader=x-response,lei1
#            - AddResponseHeader=x-response,lei1
#            - AddResponseHeader=x-response,lei2
#            - AddResponseHeader=x-response,lei2
#            - AddResponseHeader=x-response,lei3
#            - AddResponseHeader=x-response,lei3
#            - AddResponseHeader=x-response,lei3
#            - DedupeResponseHeader=x-response,RETAIN_FIRST
#            - MapRequestHeader=test-header, Authorization
#            - PrefixPath=/lei
#            - StripPrefix=1
#            - SetRequestHeader=X-Request-lei, gold
#            - SetRequestHeader=X-Request-lei, zsls
#            - SetStatus=401
#            - RemoveRequestHeader=X-Request-lei
#            - RemoveRequestParameter=name
#            - RemoveResponseHeader=x-response
      #如配置服务名路由无效时，可放开此配置
          metadata:
            response-timeout: 200
            connect-timeout: 200

#      discovery:
#        locator:
#          enabled: true

    #开始配置consul的服务注册
    consul:
      #consul服务器的主机地址 默认:localhost
      host: localhost
      #consul服务器的ip地址 默认:8500
      port: 8500
      discovery:
        #是否需要注册
        register: true
        #注册的实例ID (唯一标志)
        instance-id: ${spring.application.name}-1
        #服务的名称
        service-name: ${spring.application.name}
        #当前服务的请求端口
        port: ${server.port}
        #指定开启ip地址注册
        prefer-ip-address: true
        #当前服务所在 ip ${spring.cloud.client.ip-address}
        ip-address: 192.168.124.17
management:
  endpoints:
    web:
      exposure:
        # 暴露所有端点，开发时可开启，生产时建议关闭
        include: "*"