server:
  port: 6001 #\u7AEF\u53E3
spring:
  application:
    #\u670D\u52A1\u540D\u79F0
    name: app-gateway
  cloud:
    gateway:
      routes:
        #\u6700\u666E\u901A\u7684\u8DEF\u7531
        - id: easy-order
          uri: http://localhost:9002/
          predicates:
            - Path=/order/**
        #\u670D\u52A1\u540D\u8DEF\u7531 \u8D1F\u8F7D\u5747\u8861
        - id: server-product
          uri: lb://demo-product
          predicates:
            - Path=/product/**,/zs/{aa}
      #\u542F\u7528DiscoveryClient\u7F51\u5173\u96C6\u6210\u7684\u6807\u5FD7,\u5982\u679C\u670D\u52A1\u540D\u8DEF\u7531\u65E0\u6548\u65F6\uFF0C\u53EF\u8BBE\u7F6E\u540E\u518D\u6B21\u5C1D\u8BD5
#      discovery:
#        locator:
#          enabled: true

    ###\u5F00\u59CB\u914D\u7F6Econsul\u7684\u670D\u52A1\u6CE8\u518C
    consul:
      #consul\u670D\u52A1\u5668\u7684\u4E3B\u673A\u5730\u5740 \u9ED8\u8BA4:localhost
      host: localhost
      #consul\u670D\u52A1\u5668\u7684ip\u5730\u5740 \u9ED8\u8BA4:8500
      port: 8500
      discovery:
        #\u662F\u5426\u9700\u8981\u6CE8\u518C
        register: true
        #\u6CE8\u518C\u7684\u5B9E\u4F8BID (\u552F\u4E00\u6807\u5FD7)
        instance-id: ${spring.application.name}-1
        #\u670D\u52A1\u7684\u540D\u79F0
        service-name: ${spring.application.name}
        #\u5F53\u524D\u670D\u52A1\u7684\u8BF7\u6C42\u7AEF\u53E3
        port: ${server.port}
        #\u6307\u5B9A\u5F00\u542Fip\u5730\u5740\u6CE8\u518C
        prefer-ip-address: true
        #\u5F53\u524D\u670D\u52A1\u6240\u5728 ip ${spring.cloud.client.ip-address}
        ip-address: 192.168.124.17
management:
  endpoints:
    web:
      exposure:
        include: "*"   #\u5F00\u542F\u6240\u6709web\u7AEF\u70B9\u66B4\u9732
