server:
  port: 9002 #端口
spring:
  application:
    #服务名称
    name: demo-order
  ###开始配置consul的服务注册
  cloud:
    consul:
      #consul服务器的主机地址 默认:localhost
      host: localhost
      #consul服务器的ip地址 默认:8500
      port: 8500
      discovery:
        #是否需要注册
        register: true
        #注册的实例ID (唯一标志)
        instance-id: ${spring.application.name}-1
        #服务的名称
        service-name: ${spring.application.name}
        #当前服务的请求端口
        port: ${server.port}
        #指定开启ip地址注册
        prefer-ip-address: true
        #当前服务所在 ip ${spring.cloud.client.ip-address}
        ip-address: 192.168.124.17

#对demo-product 服务设置负载均衡策略为随机
demo-product:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule #配置规则 随机

feign:
  httpclient:
    enabled: true
  client:
    config:
      #demo-product 服务超时时间设置
      demo-product:
        #显示调用日志
        loggerLevel: full
        #连接超时时间
        connectTimeout: 5000
        #读取超时时间
        readTimeout: 5000
      #全部服务提供者超时时间设置
      default:
        #显示调用日志
        loggerLevel: full
        #连接超时时间
        connectTimeout: 3000
        #读取超时时间
        readTimeout: 3000
  hystrix:
    #feign开启hystrix支持
    enabled: true
hystrix:
  command:
    default:  #default全局有效，service id指定应用有效
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 5000 #断路器超时时间，默认1000ms
          strategy: SEMAPHORE
logging:
  level:
    com.leilei.demo: debug

